[default]
duration = "5m"
sorting = "random"
mode = "fit-border-color"

[any]
path = "/home/laura/Pictures/アニメ/東方/ぬえ/"

["LG Electronics LG ULTRAGEAR 011NTYT3V010"]
path = "/home/laura/Pictures/wallpapers/pastel.jpg"
mode = "center"
