[default]
path = "/home/laura/Pictures/wallpapers/16-9"
duration = "5m"
sorting = "random"
mode = "center"
[DP-1]
path = "/home/laura/Pictures/wallpapers/rsynced"
duration = "5m"
sorting = "random"
mode = "center"
