[default]
duration = "5m"
sorting = "random"
mode = "center"

[any]
path = "/home/laura/Pictures/wallpapers/16-9"

["LG Electronics LG ULTRAGEAR 011NTYT3V010"]
path = "/home/laura/Pictures/wallpapers/pastel.jpg"
