context.modules = [
	{ name = libpipewire-module-filter-chain
		flags = [ nofail ]
		args = {
			node.description = "Downmix Mono"
			media.name = "Downmix Mono"
			filter.graph = {
				nodes = [
					# duplicate inputs
					{ type = builtin label = copy name = copyFL  }
					{ type = builtin label = copy name = copyFR  }
					{ type = builtin label = copy name = copyFC  }
					{ type = builtin label = copy name = copyRL  }
					{ type = builtin label = copy name = copyRR  }
					{ type = builtin label = copy name = copySL  }
					{ type = builtin label = copy name = copySR  }
					{ type = builtin label = copy name = copyLFE }

					# stereo output
					{ type = builtin label = mixer name = mixL }
					{ type = builtin label = mixer name = mixR }
				]
				links = [
					{ output = "copyFL:Out"  input="mixL:In 1" }
					{ output = "copyFL:Out"  input="mixR:In 1" }
					{ output = "copyFR:Out"  input="mixL:In 2" }
					{ output = "copyFR:Out"  input="mixR:In 2" }
					{ output = "copyFC:Out"  input="mixL:In 3" }
					{ output = "copyFC:Out"  input="mixR:In 3" }
					{ output = "copyRL:Out"  input="mixL:In 4" }
					{ output = "copyRL:Out"  input="mixR:In 4" }
					{ output = "copyRR:Out"  input="mixR:In 5" }
					{ output = "copyRR:Out"  input="mixL:In 5" }
					{ output = "copySL:Out"  input="mixR:In 6" }
					{ output = "copySL:Out"  input="mixL:In 6" }
					{ output = "copySR:Out"  input="mixR:In 7" }
					{ output = "copySR:Out"  input="mixL:In 7" }
					{ output = "copyLFE:Out" input="mixR:In 8" }
					{ output = "copyLFE:Out" input="mixL:In 8" }
				]
				inputs  = [ "copyFL:In" "copyFR:In" "copyFC:In" "copyLFE:In" "copyRL:In" "copyRR:In", "copySL:In", "copySR:In" ]
				outputs = [ "mixL:Out" "mixR:Out" ]
			}
			capture.props = {
				node.name = "effect_input.downmix-mono"
				audio.channels = 8
				audio.position = [ FL FR FC LFE RL RR SL SR ]
				target.object = "effect_output.loopback"
			}
			playback.props = {
				node.name = "effect_output.downmix-mono"
				audio.channels = 2
				audio.position = [ FL FR ]
				stream.dont-remix = true
				target.object = "alsa_output.pci-0000_7a_00.6.analog-stereo"
			}
		}
	}
]

