context.modules = [
	{   name = libpipewire-module-loopback
		args = {
			node.description = "Loopback"
			audio.position = [ FL FR FC LFE RL RR SL SR ]
			capture.props = {
				node.name = "effect_input.loopback"
				media.class = "Audio/Sink"
			}
			playback.props = {
				node.name = "effect_output.loopback"
				node.passive = true
				stream.dont-remix = true
			}
		}
	}
]
