context.properties = {
	default.clock.allowed-rates = [ 48000 ]
}
stream.properties = {
	stream.dont-remix        = true
	channelmix.disable       = true
	channelmix.upmix         = false
	## only "psd", "none" or "simple" values are accepted
	channelmix.upmix-method  = none
}
