# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
		{ device = "/dev/mapper/luks-root";
			fsType = "f2fs";
			options = [ "atgc" "gc_merge" "noatime" ];
		};

	boot.initrd.luks.devices = {
		"luks-root".device = "/dev/disk/by-uuid/0f9255b8-d170-4748-adf1-ad4ea7d686c4";
			"luks-root".allowDiscards = true;
			"luks-root".bypassWorkqueues = true;
			"luks-root".crypttabExtraOpts = [ "tpm2-device=auto" ];
		"luks-swap".device = "/dev/disk/by-uuid/6b5c817d-389a-4bca-b67b-bf8c5b736c4e";
			"luks-swap".allowDiscards = true;
			"luks-swap".bypassWorkqueues = true;
			"luks-swap".crypttabExtraOpts = [ "tpm2-device=auto" ];
	};

	fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/7729-7037";
		fsType = "vfat";
		options = [ "fmask=0077" "dmask=0077" ];
		};

	swapDevices =
		[ { device = "/dev/mapper/luks-swap"; }
		];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
