monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Topping_DX3_Pro_-00.HiFi__Headphones__sink"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S32_LE"
        audio.rate = 96000
        # Following value should be doubled until audio does not cut out or other issues stop occurring
        api.alsa.period-size = 128
        api.alsa.headroom = 0
        api.alsa.disable-batch = true
      }
    }
  }
]
