# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/605a909c-0c0c-40b8-a57f-eea224baf3a8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dc90d2b3-cb4f-4671-8003-3c7f7169b3bf".device = "/dev/disk/by-uuid/dc90d2b3-cb4f-4671-8003-3c7f7169b3bf";
  boot.initrd.luks.devices."luks-8e2f7c65-f631-461b-be97-9ed234ab4ccd".device = "/dev/disk/by-uuid/8e2f7c65-f631-461b-be97-9ed234ab4ccd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8072-71F7";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8451b46a-802c-437d-9e34-32e40cf54bd2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
