monitor=eDP-1,preferred,auto,1

device {
  name = at-translated-set-2-keyboard
  kb_layout = de
}

device {
  name = alpsps/2-alps-dualpoint-stick
  sensitivity = -0.6
}

device {
  name = alpsps/2-alps-dualpoint-touchpad
  accel_profile = flat
  sensitivity = -0.4
  tap-to-click = false
  natural_scroll = true
}
