[[shades]]
name = "blue-light-filter-5500"
start_time = 19:00:00
[[shades]]
name = "blue-light-filter-5000"
start_time = 19:20:00
[[shades]]
name = "blue-light-filter-4500"
start_time = 19:40:00
[[shades]]
name = "blue-light-filter-4000"
start_time = 20:00:00
[[shades]]
name = "blue-light-filter-3500"
start_time = 20:20:00
[[shades]]
name = "blue-light-filter-3000"
start_time = 20:40:00
[[shades]]
name = "blue-light-filter-2500"
start_time = 21:00:00
end_time = 04:00:00

