monitor=desc:LG Electronics LG ULTRAGEAR 011NTYT3V010,		highrr,		0x0,		1
monitor=desc:Acer Technologies Acer K242HYL T41EE0014202,	highres,	-200x-1080,	1
monitor=desc:Ancor Communications Inc VG248 F4LMQS084305,	highres,	1720x-1080,	1
monitor=Unknown-1,disable

exec-once = qpwgraph -a /home/laura/Documents/patchbay-k553.qpwgraph -m -x
exec = xrandr --output $(xrandr --listactivemonitors | grep 3440 | awk '{print $NF}') --primary
