monitor=desc:LG Electronics LG ULTRAGEAR 011NTYT3V010,		3440x1440@160,	0x0,		1
monitor=desc:Acer Technologies Acer K242HYL T41EE0014202,	highres,		-200x-1080,	1
monitor=desc:Ancor Communications Inc VG248 F4LMQS084305,	highres,		1720x-1080,	1
monitor=Unknown-1,disable


workspace = 1, monitor:desc:LG Electronics LG ULTRAGEAR 011NTYT3V010, default:true


exec = xrandr --output $(xrandr --listactivemonitors | grep 3440 | awk '{print $NF}') --primary
exec = openrgb -p "various pinks.orp" && sleep 5 && openrgb -p "various pinks.orp"

exec-once = hyprshade install
exec-once = systemctl --user enable --now hyprshade.timer
exec = hyprshade auto

exec-once = [workspace 1] $screen_lock && (floorp & anki & steam &)


cursor {
	default_monitor = desc:LG Electronics LG ULTRAGEAR 011NTYT3V010
}

workspace = w[tv1]s[false]m[desc:Acer Technologies Acer K242HYL T41EE0014202], gapsout:0, gapsin:0, rounding:false
workspace = w[tv1]s[false]m[desc:Ancor Communications Inc VG248 F4LMQS084305], gapsout:0, gapsin:0, rounding:false
workspace = w[tv1]s[false]m[desc:LG Electronics LG ULTRAGEAR 011NTYT3V010], gapsout:20 600
