general {
  lock_cmd = pidof swaylock || swaylock -e -i /home/laura/Pictures/wallpapers/66035612_p0.png --bs-hl-color ff0000ff --indicator-idle-visible --indicator-radius 100 --inside-color 00000000 --key-hl-color ffffffff --ring-color bbbbbbff       # avoid starting multiple hyprlock instances.
  before_sleep_cmd = loginctl lock-session    # lock before suspend.
  inhibit_sleep = 3
}
