monitor=DP-1,3440x1440@160,0x0,1
monitor=DP-2,1920x1080@60,2720x-1080,1
monitor=HDMI-A-1,1920x1080@60,800x-1080,1

workspace=6, monitor:HDMI-A-1, default:true
workspace=1, monitor:DP-1, default:true
workspace=10, monitor:DP-2,default:true
workspace=5, monitor:DP-1, on-created-empty: steam %U
workspace=7, monitor:HDMI-A-1, on-created-empty: quodlibet


input {
  kb_layout = us
  numlock_by_default = true

  follow_mouse = 1

  sensitivity = -0.5
  accel_profile = flat
}
